name: dart_test_tools
description: Additional tools and helpers for writing dart unit tests.
version: 1.0.0
homepage: https://github.com/Skycoder42/dart_test_tools

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  args: ^2.2.0
  pubspec_parse: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  dart_pre_commit: ^2.3.2
  lint: ^1.6.0

executables:
  test: test
