name: dart_test_tools
description: Additional tools and helpers for writing dart unit tests.
version: 0.1.0
homepage: https://github.com/Skycoder42/dart_test_tools

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  args: ^2.3.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.2.0
  yaml: ^3.1.0
  yaml_writer: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.7
  dart_pre_commit: ^2.3.3
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  lint: ^1.8.1

executables:
  test: test
  publish: publish
  import_analyzer: import_analyzer
