name: dart_test_tools
description: Additional tools and helpers for writing dart unit tests.
version: 1.0.0
homepage: https://github.com/Skycoder42/dart_test_tools

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  args: ^2.3.0
  freezed_annotation: ^1.0.0
  logging: ^1.0.2
  path: ^1.8.0
  pubspec_parse: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  dart_pre_commit: ^2.3.3
  freezed: ^1.0.2
  lint: ^1.7.2

executables:
  test: test
