on:
  workflow_call:
    inputs:
      # checkout and build paths
      repository:
        type: string
        required: false
        description: The repository to check out. Passed as "repository" to "actions/checkout"
      workingDirectory:
        type: string
        required: false
        default: "."
        description: The root directory of the dart package to build and test
      buildRunner:
        type: boolean
        required: false
        default: false
        description: Specify whether build_runner is used in the project (defaults to false)
      # static analysis
      publishExclude:
        type: string
        required: false
        description: Specify a list of colon separated paths to be excluded from publishing
      # unit tests & coverage
      unitTestPaths:
        type: string
        required: false
        description: >-
          Specifiy directories or paths of unit tests to run.
          By default, all test discoverable by dart test are run
      minCoverage:
        type: number
        required: false
        default: 95
        description: >-
          Minimal coverage (in percent) required for the CI to succeed.
          Passed as "min_coverage" to "VeryGoodOpenSource/very_good_coverage"
      coverageExclude:
        type: string
        required: false
        description: >-
          Files to exclude from test coverage.
          Passed as "exclude" to "VeryGoodOpenSource/very_good_coverage"
      # integration tests
      integrationTestPaths:
        type: string
        required: false
        description: >-
          Specifiy directories or paths of integration tests to run.
          By default, no integration test are run
      integrationTestSetup:
        type: string
        required: false
        description: |
          A JSON-Matrix with extra setup steps for each platform.
          contains key-value pairs for each platform with a command to be invoked.

          Example:
          {
            "linux": "dart run tools/install-deps.dart",
            "web": "./setup-web.sh"
          }
      # general config
      dartSdkVersion:
        type: string
        required: false
        default: stable
        description: The Dart-SDK version. Passed as "sdk" to "dart-lang/setup-dart"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Install dart SDK (${{ inputs.dartSdkVersion }})
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Checkout repository ${{ inputs.repository }}
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
      - name: Restore dart packages
        run: dart pub get
        working-directory: ${{ inputs.workingDirectory }}
      - name: Create build files
        if: inputs.buildRunner
        run: dart run build_runner build
        working-directory: ${{ inputs.workingDirectory }}

      - name: Static analysis
        run: dart analyze --fatal-infos
        working-directory: ${{ inputs.workingDirectory }}
      - name: Validate correct formatting
        run: dart format -onone --set-exit-if-changed .
        working-directory: ${{ inputs.workingDirectory }}
      - name: Test publishing configuration
        run: |
          set -e
          if [[ ! -z "${{ inputs.publishExclude }}" ]]; then
            IFS=':'
            for path in "${{ inputs.publishExclude }}"; do
              git rm "$path"
            done
          fi
          exec dart pub publish --dry-run
        working-directory: ${{ inputs.workingDirectory }}

  unit_tests:
    name: Unit tests
    needs:
      - analyze
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - windows
          - macos
          - web

        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
          - platform: web
            os: ubuntu-latest
            dartTestArgs: -p chrome

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dart SDK (${{ inputs.dartSdkVersion }})
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Checkout repository ${{ inputs.repository }}
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
      - name: Restore dart packages
        run: dart pub get
        working-directory: ${{ inputs.workingDirectory }}
      - name: Create build files
        if: inputs.buildRunner
        run: dart run build_runner build
        working-directory: ${{ inputs.workingDirectory }}

      - name: Run unit tests
        run: dart test ${{ matrix.dartTestArgs }} --coverage=coverage ${{ inputs.unitTestPaths }}
        working-directory: ${{ inputs.workingDirectory }}

      - name: Transform coverage files
        run: >-
          dart run coverage:format_coverage
          --lcov
          --check-ignore
          --in=coverage
          --out=coverage/lcov.info
          --packages=.packages
          --report-on=lib
        working-directory: ${{ inputs.workingDirectory }}
      - name: Validate coverage is at least ${{ inputs.minCoverage }}%
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ${{ inputs.workingDirectory }}/coverage/lcov.info
          min_coverage: ${{ inputs.minCoverage }}
          exclude: ${{ inputs.coverageExclude }}

  integration_tests:
    name: Integration tests
    if: "inputs.integrationTestPaths != ''"
    needs:
      - analyze
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - windows
          - macos
          - web

        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
          - platform: web
            os: ubuntu-latest
            dartTestArgs: -p chrome

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dart SDK (${{ inputs.dartSdkVersion }})
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - name: Checkout repository ${{ inputs.repository }}
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
      - name: Restore dart packages
        run: dart pub get
        working-directory: ${{ inputs.workingDirectory }}
      - name: Create build files
        if: inputs.buildRunner
        run: dart run build_runner build
        working-directory: ${{ inputs.workingDirectory }}

      - name: Run platform test setup
        if: "fromJSON(inputs.integrationTestSetup)[matrix.platform] != ''"
        run: ${{ fromJSON(inputs.integrationTestSetup)[matrix.platform] }}
        working-directory: ${{ inputs.workingDirectory }}

      - name: Run integration tests
        run: dart test ${{ matrix.dartTestArgs }} ${{ inputs.integrationTestPaths }}
        working-directory: ${{ inputs.workingDirectory }}
