on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: false
        description: The repository to check out. Passed as "repository" to "actions/checkout"
      workingDirectory:
        type: string
        required: false
        description: The root directory of the dart package to build and test
      buildRunner:
        type: boolean
        required: false
        default: false
        description: Specify whether build_runner is used in the project (defaults to false)
      publishExclude:
        type: string
        required: false
        description: Specify a list of colon separated paths to be excluded from publishing
      dartSdkVersion:
        type: string
        required: false
        default: stable
        description: The Dart-SDK version. Passed as "sdk" to "dart-lang/setup-dart"

jobs:
  analyze:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ inputs.dartSdkVersion }}
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
      - run: dart pub get
        name: Restore dart packages
        working-directory: ${{ inputs.workingDirectory }}
      - run: dart run build_runner build
        name: Create build files
        if: inputs.buildRunner
        working-directory: ${{ inputs.workingDirectory }}
      - run: dart analyze --fatal-infos
        name: Static analysis
        working-directory: ${{ inputs.workingDirectory }}
      - run: dart format -onone --set-exit-if-changed .
        name: Validate correct formatting
        working-directory: ${{ inputs.workingDirectory }}
      - run: |
          set -e
          IFS=':'
          for path in "${{ inputs.publishExclude }}"; do
            git rm "$path"
          done
        name: Remove files not to be published
        if: inputs.publishExclude.length > 0
        working-directory: ${{ inputs.workingDirectory }}
      - run: dart pub publish --dry-run
        name: Test publishing configuration
        working-directory: ${{ inputs.workingDirectory }}
